### ISSUE TITLE
create/topic panic

### ISSUE THREAD

**Issue by absolute8511** [youzan/nsq#4]
_From @weisd on May 7, 2017 3:50_

docker运行了 nsqd,nsqlookupd,nsqadmin

调用创建topic时返回500， INTERNAL_ERROR

http://localhost:4161/topic/create?topic=test&partition_num=1&replicator=1

看了下日志如果
```
I0506 13:30:47.069194   20696 router.go:273] httprouter.(*Router).recv ERROR: panic in HTTP handler - runtime error: invalid memory address or nil pointer dereference
```
是不是少了什么程序，还是bug? 其他ping接口正常

_Copied from original issue: absolute8511/nsq#22_

**Comment by absolute8511** [comment]
_From @weisd on May 7, 2017 4:56_

输出了一下runtime.Stack, 调用了未定义的ctx  s.ctx.nsqlookupd.coordinator.IsMineLeader() 
coordinator在哪里赋值？@absolute8511

**Comment by absolute8511** [comment]
是不是没有配置`cluster_id` 和`cluster_leadership_addresses`

**Comment by absolute8511** [comment]
_From @liushuchun on May 8, 2017 2:14_

可能是cluster 集群没配置，我最后配置好，很好用。

**Comment by absolute8511** [comment]
_From @weisd on May 8, 2017 2:45_

这是我的docker-composer
```
version: '2'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    ports:
      - "4171:4171"
```
@absolute8511 @liushuchun  cluster_id, cluster_leadership_addresses 应该写在哪？
